name: Deploy no Kubernetes
on:
    workflow_call:
        inputs:
            manifests:
                type: string
                required: true
                description: "Arquivos de manifesto para deploy"
            images:
                type: string
                required: true
                description: "Imagens que serão alteradas nos manifestos"
jobs:
    deploy-k8s:
        runs-on: ubuntu-latest
        steps:
        - name: obtendo o código
          uses: actions/checkout@v4.2.2
        - name: Configuração de contexto do Kubernetes
          uses: azure/k8s-set-context@v4.0.1
          with:
            method: kubeconfig
            kubeconfig: ${{ secrets.KUBE_CONFIG }}
        - uses: Azure/k8s-deploy@v5
          with:
            manifests: ${{ inputs.manifests }}
            images: ${{ inputs.imagens }}