name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: obtendo o código
        uses: actions/checkout@v4.2.2
      - name: Autenticação no docker
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build da imagem docker
        uses: docker/build-push-action@v6.15.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            itamarbf/aula-primeira-pipeline:v${{ github.run_number }}
            itamarbf/aula-primeira-pipeline:latest
  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: obtendo o código
        uses: actions/checkout@v4.2.2
      - name: Configuração de contexto do Kubernetes
        uses: azure/k8s-set-context@v4.0.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            ./k8s/deployment.yaml
          images: |
            itamarbf/aula-primeira-pipeline:v${{ github.run_number }}
