name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: obtendo o código
        uses: actions/checkout@v4.2.2
      - name: Autenticação no docker
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build da imagem docker
        uses: docker/build-push-action@v6.15.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            itamarbf/aula-primeira-pipeline:v${{ github.run_number }}
            itamarbf/aula-primeira-pipeline:latest
  CD:
    needs: [CI]
    uses: itamar-devops-pro/segunda-pipeline-cicd/.github/workflows/deploy.yaml@main
    with:
      manifests: k8s/deployment.yaml
      images: itamarbf/aula-primeira-pipeline:v${{ github.run_number }}
    secrets: inherit
